#!/usr/bin/env bash
# Paper Table 3, honestly: train each ablation variant, then evaluate it on the same clip pool.
#
#   bash scripts/run_table3.sh                       # real local pool (5 ETH3D/dense clips)
#   bash scripts/run_table3.sh configs/data/scannet.local.yaml runs/table3_scannet
#
# Variants only differ in the L4AR fields the paper names (fixed grid resampling, the learned 3D
# convolution, frame-wise attention, global attention). Each variant gets its own training run, since
# evaluating untrained variants would produce a table that looks comparable but proves nothing.
set -euo pipefail
export PYTHONUNBUFFERED=1   # keep piped logs live instead of flushing only per 4 KB
cd "$(dirname "$0")/.."

DATA=${1:-configs/data/real.yaml}
OUT=${2:-runs/table3}
PY=${PY:-/home/zbf/Desktop/dl_env/bin/python}
BASE=${BASE:-configs/model/l4ar_probe.yaml}
DEVICE=${DEVICE:-cuda}
STEPS=${STEPS:-1500}
mkdir -p "$OUT" configs/model/generated

for variant in "Full" "w/o Grid" "w/o 3D Conv" "w/o Frame" "w/o Global"; do
  slug=$(echo "$variant" | tr " /" "__")
  gen="configs/model/generated/table3_${slug}.yaml"
  $PY - "$BASE" "$gen" "$variant" <<'PY'
import re, sys
base, gen, variant = sys.argv[1:4]
overrides = {
    "w/o Grid":    {"grid_mode": "none"},
    "w/o 3D Conv": {"use_local_conv": "false"},
    "w/o Frame":   {"scope_policy": "global_only"},
    "w/o Global":  {"scope_policy": "frame_only"},
    "Full":        {},
}[variant]
text = open(base, encoding="utf-8").read()
body = "".join(f"  {key}: {value}\n" for key, value in overrides.items())
text = (f"# generated by scripts/run_table3.sh for the '{variant}' ablation\n"
        f"_base_: ../{base.split('/')[-1]}\n\nmodel:\n{body}" if body else
        f"# generated by scripts/run_table3.sh for the '{variant}' ablation\n"
        f"_base_: ../{base.split('/')[-1]}\n\nmodel: {{}}\n")
open(gen, "w", encoding="utf-8").write(text)
print(f"[variant] {variant}: {overrides or 'no overrides'} -> {gen}")
PY
  if [ ! -f "$OUT/$slug/stage3_lora.pt" ]; then
    $PY tools/train.py --model "$gen" --data "$DATA" --device "$DEVICE" --steps "$STEPS" --output "$OUT/$slug" \
      | grep -aE "activated|step ${STEPS}/${STEPS}|saved" | tail -3
  else
    echo "[skip] $variant already trained ($OUT/$slug)"
  fi
  $PY tools/eval_gt.py --model "$gen" --data "$DATA" --benchmark local_pool --device "$DEVICE" \
      --variants "Full" --checkpoint "$OUT/$slug/stage3_lora.pt" | sed "s|^Full |$variant (trained) |"
done

echo
echo "paper Table 3 for comparison (7-Scenes / NRGBD, Acc/Comp in cm, NC higher is better):"
$PY - <<'PY'
from l4d.eval.protocol import TABLE_3_REFERENCE
for variant, rows in TABLE_3_REFERENCE.items():
    seven, nrgbd = rows["7scenes"], rows["nrgbd"]
    print(f"  {variant:14s} 7S Acc={seven['Acc']:6.3f} Comp={seven['Comp']:6.3f} NC={seven['NC']:.3f}"
          f" | NRGBD Acc={nrgbd['Acc']:6.3f} Comp={nrgbd['Comp']:6.3f} NC={nrgbd['NC']:.3f}")
PY
